### ISSUE TITLE
موسسة بن معلاق

### ISSUE THREAD

**Issue by aseeralmeem** [pirate/bookmark-archiver#77] opened 2018-05-23 13:10 UTC
➜ ~/D/C/bookmark-archiver py[archiver] ⎇ (ssl-check) ./archive.py "https://medium.com/feed/@thesquashsh"
[*] [2018-01-12 12:23:50] Downloading https://medium.com/feed/@thesquashsh > downloads/medium.com.txt
[X] No links found :(
[1]

**Comment by pirate** [comment] 2018-05-24 19:17
Duplicate of https://github.com/pirate/bookmark-archiver/issues/64

**Closed by pirate** 2018-05-24 19:17 UTC
