### ISSUE TITLE
DOM Dump of the HTML of Pocket format page

### ISSUE THREAD

**Issue by mccvi** [pirate/bookmark-archiver#122] opened 2018-12-05 06:10 UTC
I would to have an option to save DOM Dump of the HTML of Pocket format page that looks like https://getpocket.com/a/read/2410101539
Because, mostly, the Pocket`s pages that were formed based on source pages are clean and easier to read.

**Comment by pirate** [comment] 2018-12-05 18:35
Duplicate of: https://github.com/pirate/bookmark-archiver/issues/69

To summarize: Pocket doesn't provide their readability view as open source software, but we can do something similar with one of the other readability programs.

**Closed by pirate** 2018-12-05 18:35 UTC
